FINAL PROJECT

In [5]:
 
class Manager:
  def __init__(self, firstname, lastname,age, language ):
     self.name1 = firstname
     self.name2 = lastname
     self.age = age
     self.lang = language
 
  def fullDetails(self):
      print(self.name1 + " " + self.name2 +" Age: " + str (self.age) + "years" +" , " +  self.lang)
 
 
Manager1= Manager("Ahmed", "Oladimeji", 32 ,"English")  
 
Manager1.fullDetails()

Ahmed Oladimeji Age: 32years , English

In [2]:
class Employee(Company):
     
     def lang1(self):
        print (self.lang)
        
 
employees = [Employee("Janice","cinco", 28,"English" ), Employee("Bola", "Ola", 25,"Spanish"), Employee("Chris ", "Mark", 26,"Turkish")] 
 
 
def list(employees):
      for employee1 in employees:
          employee1.lang1()
list(employees)

English
Spanish
Turkish